language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t tjaktor/dockerizing-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true tjaktor/dockerizing-react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "dockerizing-react-app"
  env: "DockerizingReactApp-env"
  bucket_name: "elasticbeanstalk-eu-north-1-107182149254"
  bucket_path: "dockerizing-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY