language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t tjaktor/dockerizing-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true tjaktor/dockerizing-react-app npm run test